apiVersion: apps/v1
kind: Deployment
metadata:
  name: deakin0
  labels:
    app: myapp
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: mynode
        image: gcr.io/cloudpass-387506/deakin_image0:latest
        ports:
        - containerPort: 8080